# Generated by Django 4.1.2 on 2022-11-10 21:13

import colorfield.fields
from django.db import migrations
import tags.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_alter_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=7, samples=None, validators=[tags.validators.HexColorValidator], verbose_name='HEX-код цвета'),
        ),
    ]
