# Generated by Django 4.1.2 on 2022-10-29 14:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(help_text='Не может быть меньше минуты!', validators=[django.core.validators.MinValueValidator(1, 'Не менее 1')], verbose_name='Время приготовления, мин.'),
        ),
    ]
