# Generated by Django 4.1.2 on 2022-11-10 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_alter_tag_color'),
        ('recipes', '0002_ingredient_alter_recipe_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(db_index=True, max_length=250, unique=True, verbose_name='Наименование ингредиента'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(to='tags.tag', verbose_name='Тэги'),
        ),
    ]
