# Generated by Django 4.1.2 on 2022-11-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_purchase_favorite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(db_index=True, error_messages={'unique': 'Такой ингридиент уже есть.'}, max_length=250, verbose_name='Наименование ингредиента'),
        ),
    ]
