# Generated by Django 4.1.2 on 2022-11-05 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_ingredientinrecipe_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientinrecipe',
            options={'default_related_name': 'ingredients_recipe', 'verbose_name': 'Количество ингредиента в рецепте', 'verbose_name_plural': 'Количество ингредиентов в рецептах'},
        ),
    ]
