# Generated by Django 4.1.2 on 2022-11-09 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_follow_self_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follow',
            field=models.ManyToManyField(through='users.Follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
