# Generated by Django 4.1.2 on 2022-11-10 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
