# Generated by Django 4.1.2 on 2022-11-10 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_follow_user_sorrow_alter_follow_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='sorrow',
            new_name='subscribe',
        ),
    ]
